######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 8 06:52:29 2009
######################################################################


# Directories

CONFIG += qt

FORMS += levelEditor.ui

HEADERS += window.h
HEADERS += glwidget.h

SOURCES += main.cpp
SOURCES += window.cpp
SOURCES += glwidget.cpp

QT +=opengl

TARGET = qtToolkit
